Architecture: "PredRNNv3"

Seed: 27

Setting: weather

Logger:
    save_dir: "experiments/"

ckpt_path: None

Checkpointer:
    save_top_k: 1
    save_last: True
    every_n_epochs: 1

Trainer:
#    strategy: 'ddp'
    accelerator: 'gpu'
    log_every_n_steps: 64
    devices: [0]  
    max_epochs: 50
    gradient_clip_val: 1

Data:
    val_batch_size: 32
    test_batch_size: 32
    train_batch_size: 32
    num_workers: 4

Task:
    loss:
        name: "MSE"

    context_length: 12
    target_length: 12
    n_stochastic_preds: 1
    metric: "MSE_w"
    optimization:
        optimizer:
            - name: AdamW
              args:
                  betas: [ 0.9, 0.999]
              lr_per_sample: 0.00000625
        lr_shedule:
            - name: MultiStepLR
              args:
                  milestones: [25, 40] #[2, 20, 50, 90]
                  gamma: 0.1

    n_log_batches: 2

    shedulers:
        -
          call_name: sampling
          name: "reverse_exp"
          args:
              r_sampling_step_1: 25000
              r_sampling_step_2: 50000
              r_exp_alpha: 2500


Model:
    patch_size: 4
    n_image: 1
    n_hidden: 128
    context_length: 12
    target_length: 12
    input_size_h: 32
    input_size_w: 64
    n_out: 1
    n_heads: 4
    num_layers: 4
    mlp_ratio: 4
    gate_act: "gelu"
    drop: 0.0
    attn_drop: 0.0
    drop_path: 0.0
    filter_size: 3






